image: node:8.11.2

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install -g node-gyp
          - npm install
          - node-gyp rebuild
          - make test